AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0b59bfac6be064b78
      InstanceType: t4g.nano
      KeyName: !Ref SSHKeyPair
  SSHKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: demo-key
